# Exploratory analysis
This notebook briefly explores and evaluates the datasets that will be used in this project. Based on the findings, 
we will preprocess the datasets and thereafter conduct the analysis.

### Notebook environment setup

In [1]:
# Import packages and libraries
%pip install 'duckdb==1.5.3' --force-reinstall

import os
import pandas as pd
import duckdb

Collecting duckdb==1.5.3
  Using cached duckdb-1.5.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (4.2 kB)
Using cached duckdb-1.5.3-cp314-cp314-macosx_11_0_arm64.whl (15.4 MB)
Installing collected packages: duckdb
  Attempting uninstall: duckdb
    Found existing installation: duckdb 1.5.3
    Uninstalling duckdb-1.5.3:
      Successfully uninstalled duckdb-1.5.3
Successfully installed duckdb-1.5.3

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: pip3.14 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

### Load and evaluate data

This project will look at the following datasets:
- cdc_places_county
- census_acs5_2023
- epa_aqs_annual_2023
- fred_series

Please visit https://ryanwaked.com/data for full information on the data

In [2]:
# Connect to the database
con = duckdb.connect('md:us_gov_db')

datasets = {
    'cdc_places_county': 'raw.cdc_places_county',
    'census_acs5_2023': 'raw.census_acs5_2023',
    'epa_aqs_annual_2023': 'raw.epa_aqs_annual_2023',
    'fred_series': 'raw.fred_series',
}

dfs = {}

for name, table in datasets.items():
    path = f'../data/raw/{name}.csv'
    if os.path.exists(path):
        dfs[name] = pd.read_csv(path)
    else:
        df = con.sql(f"SELECT * FROM {table}").df()
        df.to_csv(path, index=False)
        dfs[name] = df

cdc_places_county_df = dfs['cdc_places_county']
census_acs5_2023_df  = dfs['census_acs5_2023']
epa_aqs_annual_2023_df = dfs['epa_aqs_annual_2023']
fred_series_df = dfs['fred_series']

Attempting to automatically open the SSO authorization page in your default browser.
Please open this link to login into your account: https://auth.motherduck.com/activate?user_code=QZLJ-ZQSM


Token successfully retrieved ✅

You can display the token and store it as an environment variable to avoid having to log in again:
  PRAGMA PRINT_MD_TOKEN;

### Brief Dataset Exploration

In [3]:
# View data
display(cdc_places_county_df.head())
display(cdc_places_county_df.shape)

,year,stateabbr,statedesc,locationname,datasource,category,measure,data_value_unit,data_value_type,data_value,...,high_confidence_limit,totalpopulation,totalpop18plus,locationid,categoryid,measureid,datavaluetypeid,short_question_text,geolocation,_loaded_at
0,2023,CA,California,Marin,BRFSS,Disability,Any disability among adults,%,Crude prevalence,27.5,...,32.0,254407,206190,06041,DISABLT,DISABILITY,CrdPrv,Any Disability,"{'type': 'Point', 'coordinates': [-122.7235549...",2026-06-19 09:34:44.331014-07:00
1,2023,CA,California,Lassen,BRFSS,Health Status,Frequent physical distress among adults,%,Crude prevalence,15.6,...,17.7,28861,23438,06035,HLTHSTAT,PHLTH,CrdPrv,Frequent Physical Distress,"{'type': 'Point', 'coordinates': [-120.5943520...",2026-06-19 09:34:44.331014-07:00
2,2023,CA,California,Lake,BRFSS,Disability,Mobility disability among adults,%,Age-adjusted prevalence,15.1,...,17.5,67878,52978,06033,DISABLT,MOBILITY,AgeAdjPrv,Mobility Disability,"{'type': 'Point', 'coordinates': [-122.7534135...",2026-06-19 09:34:44.331014-07:00
3,2023,CA,California,Kern,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults,%,Crude prevalence,31.9,...,36.6,913820,654092,06029,RISKBEH,LPA,CrdPrv,Physical Inactivity,"{'type': 'Point', 'coordinates': [-118.7300290...",2026-06-19 09:34:44.331014-07:00
4,2023,CA,California,Glenn,BRFSS,Disability,Any disability among adults,%,Crude prevalence,35.7,...,41.1,28129,20659,06021,DISABLT,DISABILITY,CrdPrv,Any Disability,"{'type': 'Point', 'coordinates': [-122.3924328...",2026-06-19 09:34:44.331014-07:00

(59082, 21)

In [4]:
display(census_acs5_2023_df.head())
display(census_acs5_2023_df.shape)

,NAME,B01003_001E,B19013_001E,B25077_001E,B25064_001E,B25071_001E,B17001_002E,B23025_003E,B23025_005E,B15003_001E,B15003_022E,B15003_023E,B15003_024E,B15003_025E,B08013_001E,B08303_001E,B25003_001E,B25003_002E,metropolitan statistical area/micropolitan statistical area,_loaded_at
0,"Boston-Cambridge-Newton, MA-NH Metro Area",4917661.0,112484.0,610900.0,1940.0,30.2,424129.0,2809193.0,135677.0,3479921.0,956390.0,571007.0,125219.0,130069.0,64916765.0,2128447.0,1925474.0,1189120.0,14460,2026-06-19 09:34:34.341087-07:00
1,"Charleston-North Charleston, SC Metro Area",817756.0,82272.0,345400.0,1488.0,30.9,89836.0,421330.0,16085.0,570635.0,142278.0,60806.0,15873.0,9012.0,9777660.0,357454.0,327420.0,224818.0,16700,2026-06-19 09:34:34.341087-07:00
2,"Los Angeles-Long Beach-Anaheim, CA Metro Area",13012469.0,93525.0,825300.0,1987.0,33.8,1618969.0,6888495.0,455764.0,9117096.0,2175480.0,834718.0,254722.0,143872.0,158071875.0,5293768.0,4464908.0,2168812.0,31080,2026-06-19 09:34:34.341087-07:00
3,"Miami-Fort Lauderdale-West Palm Beach, FL Metr...",6138876.0,73481.0,405600.0,1770.0,37.2,794980.0,3212506.0,160940.0,4429878.0,967281.0,399532.0,148439.0,62396.0,76367010.0,2605715.0,2311230.0,1394735.0,33100,2026-06-19 09:34:34.341087-07:00
4,"New York-Newark-Jersey City, NY-NJ Metro Area",19756722.0,97334.0,587400.0,1780.0,31.0,2416274.0,10412496.0,681021.0,13911545.0,3465456.0,1856167.0,480223.0,249280.0,290532525.0,8074340.0,7362500.0,3789974.0,35620,2026-06-19 09:34:34.341087-07:00

(14, 20)

In [5]:
display(epa_aqs_annual_2023_df.head())
display(epa_aqs_annual_2023_df.shape)

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,...,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change,_query_cbsa,_query_param,_loaded_at
0,53,033,2004,88101,5,47.386111,-122.230278,WGS84,PM2.5 - Local Conditions,1,...,"614 RAILROAD AVE N, KENT",Washington,King,Kent,42660,"Seattle-Tacoma-Bellevue, WA",2024-05-17,42660,88101,2026-06-19 09:34:27.663212-07:00
1,53,033,2004,88101,5,47.386111,-122.230278,WGS84,PM2.5 - Local Conditions,X,...,"614 RAILROAD AVE N, KENT",Washington,King,Kent,42660,"Seattle-Tacoma-Bellevue, WA",2024-05-17,42660,88101,2026-06-19 09:34:27.663212-07:00
2,53,033,2004,88101,5,47.386111,-122.230278,WGS84,PM2.5 - Local Conditions,X,...,"614 RAILROAD AVE N, KENT",Washington,King,Kent,42660,"Seattle-Tacoma-Bellevue, WA",2024-05-17,42660,88101,2026-06-19 09:34:27.663212-07:00
3,53,033,2004,88101,5,47.386111,-122.230278,WGS84,PM2.5 - Local Conditions,X,...,"614 RAILROAD AVE N, KENT",Washington,King,Kent,42660,"Seattle-Tacoma-Bellevue, WA",2024-05-17,42660,88101,2026-06-19 09:34:27.663212-07:00
4,53,033,2004,88101,5,47.386111,-122.230278,WGS84,PM2.5 - Local Conditions,X,...,"614 RAILROAD AVE N, KENT",Washington,King,Kent,42660,"Seattle-Tacoma-Bellevue, WA",2024-05-17,42660,88101,2026-06-19 09:34:27.663212-07:00

(3356, 59)

In [6]:
display(fred_series_df.head())
display(fred_series_df.shape)

,date,value,series_id,label,_loaded_at
0,1948-01-01,3.4,UNRATE,US unemployment rate,2026-06-19 09:34:35.689909-07:00
1,1948-02-01,3.8,UNRATE,US unemployment rate,2026-06-19 09:34:35.689909-07:00
2,1948-03-01,4.0,UNRATE,US unemployment rate,2026-06-19 09:34:35.689909-07:00
3,1948-04-01,3.9,UNRATE,US unemployment rate,2026-06-19 09:34:35.689909-07:00
4,1948-05-01,3.5,UNRATE,US unemployment rate,2026-06-19 09:34:35.689909-07:00

(1597, 5)